#!/usr/bin/env node
/**
 * Builds the rich-text editor page the app shows in a WebView: TipTap with
 * the web's extensions (editor-web/ + ../lib/rich-text), bundled with its CSS
 * into ONE self-contained HTML string, written to
 * src/editor/editor-html.generated.ts (not versioned — every script that
 * bundles the app runs this first).
 *
 * TipTap comes from the WEB's node_modules, on purpose: the page must run the
 * very same TipTap build the web runs, so a note serialises identically on
 * both. The root project has to be installed (`pnpm install` in the repo
 * root) before the app can be built.
 *
 * The page loads nothing: no network, no files. The build enforces it — the
 * page carries a Content-Security-Policy that allows no origin at all and
 * only this exact script (by hash), and the build fails if the bundle
 * references a URL it does not know to be inert.
 */
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const mobile = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repo = path.resolve(mobile, "..");
const out = path.join(mobile, "src/editor/editor-html.generated.ts");

if (!existsSync(path.join(repo, "node_modules/@tiptap/core"))) {
  console.error(
    "build-editor: the web's dependencies are not installed. Run `pnpm install` in the repo root first."
  );
  process.exit(1);
}

/**
 * Our sources' @tiptap/* imports resolve from the repo root — the web's copy —
 * even if this project ever installs a TipTap of its own. Imports between
 * TipTap's packages then follow the web's node_modules on their own.
 */
const tiptapFromWeb = {
  name: "tiptap-from-web",
  setup(b) {
    b.onResolve({ filter: /^@tiptap\// }, async (args) => {
      if (args.pluginData === "tiptap-from-web" || args.importer.includes("/node_modules/")) {
        return undefined;
      }
      const result = await b.resolve(args.path, {
        kind: args.kind,
        resolveDir: repo,
        pluginData: "tiptap-from-web",
      });
      return result.errors.length ? { errors: result.errors } : { path: result.path };
    });
  },
};

const bundle = await build({
  entryPoints: [path.join(mobile, "editor-web/main.ts")],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  // Android System WebView is evergreen Chromium; this is a floor, not a guess.
  target: ["chrome100"],
  minify: true,
  legalComments: "eof",
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [tiptapFromWeb],
  logLevel: "warning",
});

const js = bundle.outputFiles[0].text;
const css = await readFile(path.join(mobile, "editor-web/page.css"), "utf8");

// The script and the style are inlined, so neither may close its own tag.
for (const [what, text, closer] of [
  ["script", js, /<\/script|<!--/i],
  ["style", css, /<\/style/i],
]) {
  if (closer.test(text)) {
    console.error(`build-editor: the ${what} contains a sequence that would end its inline tag.`);
    process.exit(1);
  }
}

// URLs in the bundle that are not fetched: XML namespaces, and links to docs
// inside TipTap's and ProseMirror's error messages. Anything else fails the
// build until someone looks at it.
const INERT_URL = [
  /^http:\/\/www\.w3\.org\//,
  /^https:\/\/tiptap\.dev\//,
  /^https:\/\/prosemirror\.net\//,
  /^https:\/\/github\.com\/ProseMirror\//,
  /^https:\/\/github\.com\/ueberdosis\//,
];
const urls = [...new Set((js + css).match(/https?:\/\/[^\s"'`)\\]+/g) ?? [])];
const unknown = urls.filter((u) => !INERT_URL.some((re) => re.test(u)));
if (unknown.length) {
  console.error("build-editor: the bundle references URLs not known to be inert:\n  " + unknown.join("\n  "));
  process.exit(1);
}

const scriptHash = createHash("sha256").update(js, "utf8").digest("base64");
const csp = [
  "default-src 'none'",
  `script-src 'sha256-${scriptHash}'`,
  // TipTap injects its base styles as a <style> element at runtime.
  "style-src 'unsafe-inline'",
  // The chip icons are data: SVG masks.
  "img-src data:",
  "base-uri 'none'",
  "form-action 'none'",
].join("; ");

const html =
  "<!doctype html>" +
  '<html lang="en"><head><meta charset="utf-8">' +
  `<meta http-equiv="Content-Security-Policy" content="${csp}">` +
  '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">' +
  `<style>${css}</style>` +
  '</head><body><div id="editor"></div>' +
  `<script>${js}</script>` +
  "</body></html>";

const sha256 = createHash("sha256").update(html, "utf8").digest("hex");
await writeFile(
  out,
  "// Generated by scripts/build-editor.mjs — do not edit, not versioned.\n" +
    "// Rebuild with `pnpm editor:build`.\n\n" +
    `export const EDITOR_HTML: string = ${JSON.stringify(html)};\n\n` +
    `export const EDITOR_HTML_SHA256 = ${JSON.stringify(sha256)};\n`
);

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(
  `build-editor: ${path.relative(mobile, out)} — ${kb(Buffer.byteLength(html))} ` +
    `(script ${kb(Buffer.byteLength(js))}), ${urls.length} inert URL(s), sha256 ${sha256.slice(0, 12)}`
);
